# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3e1ca66b03ca1806a3c802e2ea07d86a48d831ca8ff696ebf270d182c0be6a7d414d5801744e5c9481afb752017a4f6380cfe44bab3a9081a2f7e28a2be9b9e

test:
  secret_key_base: 13a79d992fdbc1502a9994c8a5986398f7aebd7ae79155945d40c3fb61924e2be33a5f6c666ec58a26038f1d8e5fac3e096f60e000fd06937098c6ea851977c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
